### ISSUE TITLE
When showing 'original', indicate the type

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#101]
In some cases, the type of the original isn't clear to the user, especially when it comes to pasting an image.

The type of the original should be indicated.

We should do this by the same mechanism we use to decide which decoder to use (https://github.com/GoogleChromeLabs/squoosh/pull/91#discussion_r201663191).

For formats with broad browser support, I wonder if the mimetype is already populated by sniffing. We should try throwing some extensionless images at the app and see what happens.

**Comment by kosamari** [comment]
Probably there is room for this in UI
<img width="324" alt="Screen Shot 2021-07-01 at 12 34 27 PM" src="https://user-images.githubusercontent.com/4581495/124159125-c4508f80-da68-11eb-8a98-322a13158223.png">

**Comment by cherinyy** [comment]
![image](https://github.com/GoogleChromeLabs/squoosh/assets/9050713/4f3e99e7-d872-4713-be3a-6502c20962fe)

![image](https://github.com/GoogleChromeLabs/squoosh/assets/9050713/cecc1f97-c985-457d-9f03-f47d3b294a53)

Currently importing original images from the clipboard causes the type to be set to unknown, hopefully the image file will be detected correctly.

**Comment by mpigagr** [comment]
I think this is solved now...

![squoosh_issue_101_test](https://github.com/GoogleChromeLabs/squoosh/assets/168282313/3bb00672-94d1-43ab-8375-11a0b763fd6a)

**Comment by cherinyy** [comment]
> I think this is solved now...
> 
> ![squoosh_issue_101_test](https://private-user-images.githubusercontent.com/168282313/329697101-3bb00672-94d1-43ab-8375-11a0b763fd6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTMyODAsIm5iZiI6MTcxNTQ1Mjk4MCwicGF0aCI6Ii8xNjgyODIzMTMvMzI5Njk3MTAxLTNiYjAwNjcyLTk0ZDEtNDNhYi04Mzc1LTExYTBiNzYzZmQ2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxODQzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDhjNjUxZjk2NzgyZTM1YjdmOTQ5MjZlMjY5MGY2ZTcyZWY2N2M4MWZhNjMzM2VlYTU1NTQzNzNkODM4Zjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w6uA6u_9quZ1N_HU4XpYv3AH1fgVzTjwYz7cYPIFKuA)

No, it's not fixed.

The issue we raised was when importing from the clipboard, rather than importing files through a file manager or similar mechanism.

**Comment by Rajkaran-122** [comment]
@jakearchibald @kosamari  sir please review this #1494 pr.
