### ISSUE TITLE
Batch processing is hanging

### ISSUE THREAD

**Issue by axelf** [GoogleChromeLabs/squoosh#1043]
**Describe the bug**
Batch processing via cli is not working. The process of converting images is endless.

**Version:**
 - OS w/ version: macOS 10.15.7
 - Node version: 14.17.0
 - npm version: 6.4.1

![Bildschirmfoto 2021-06-04 um 15 56 54](https://user-images.githubusercontent.com/1690324/120812676-7fab0480-c54d-11eb-9628-595ac3feff2e.png)

**Comment by surma** [comment]
Are there any errors being logged? Because there was a bug with errors making the CLI break that I only recently fixed.

**Comment by rayriffy** [comment]
After a lot of image processing, I've seen a pattern that `squoosh` cli cannot handle a very large batch no more than 30 files when maximum listener, or memory is reached. I wonder is it possible to separate decoding, and encoding image into one async worker and throttle them into a queue would solve this issue.

![image](https://user-images.githubusercontent.com/22584594/120869033-639c7700-c5d0-11eb-924f-3b1db13d6408.png)

**Comment by axelf** [comment]
@surma how can i see the error log? I only see the processing of all the images but the process will never be finished.

**Comment by surma** [comment]
I just published `@squoosh/cli` v0.7.1 which fixes the error handling and should fix this issue.

I’ll close this bug, but please re-open if it’s still breaking for you!

**Comment by axelf** [comment]
Hi,

@surma 
it is still not working. The same behaviour. Single files are working but a whole folder with subfolders is not working.
![Bildschirmfoto 2021-06-21 um 09 46 06](https://user-images.githubusercontent.com/1690324/122726179-0cf09780-d276-11eb-91c5-4cb27318e289.png)

**Comment by den1a** [comment]
Hi.
I have a similar problem.

![Clip2net_210621155752](https://user-images.githubusercontent.com/45651923/122770716-65dc2200-d2ae-11eb-8832-234e32d3a802.png)

Here is a photo for an example.
https://disk.yandex.ru/i/ziCmVyUsZqQLog

squoosh-cli -V
0.6.4

**Comment by surma** [comment]
@den1a can you do me a favor and re-run that with v0.7.1?

**Comment by den1a** [comment]
There are problems in the new version :)

![line](https://user-images.githubusercontent.com/45651923/122812146-fd0a9f00-d2d9-11eb-903a-a81fc6018974.png)

Windows 7

node -v
13.14.0

squoosh-cli -V
0.7.1

**Comment by surma** [comment]
Yeah, your node version is unsupported. We only support

https://github.com/GoogleChromeLabs/squoosh/blob/dbb31a1addd420423c2be7199bbdee8299aa24eb/cli/package.json#L23

(Future releases of the Squoosh CLI will emit a warning, we just merged #1061.)

**Comment by den1a** [comment]
I had to upgrade from Windows 7 to Windows 10 :)
Unfortunately the problem remained.

![console](https://user-images.githubusercontent.com/45651923/122914917-d6914600-d363-11eb-952f-177602fc6755.png)

Windows 10

node -v
16.3.0

squoosh-cli -V
0.7.1

**Comment by surma** [comment]
Thank you! I’ll investigate. My hunch is that this is related to Windows.

**Comment by den1a** [comment]
Launched docker, but the problem remained
https://hub.docker.com/_/node/

![Clip2net_2021-06-23_09_42_34](https://user-images.githubusercontent.com/45651923/123053816-f597e280-d40c-11eb-9298-89f1a07fa2f1.png)

Debian 10

node -v
16.3.0

squoosh-cli
0.7.1

Here is a photo for an example.
![000045340_allcms_p_l](https://user-images.githubusercontent.com/45651923/123054275-617a4b00-d40d-11eb-86a2-d9ed2dff1e34.jpg)

**Comment by jcao219** [comment]
I am able to reproduce @den1a 's issue (hanging on Decoding) on Windows. Problem even persists on WSL. Investigating

Edit: I think the culprit is this line here: https://github.com/GoogleChromeLabs/squoosh/blob/149ebf5a67966cbc3a406e693f6973bc9877891a/codecs/mozjpeg/dec/mozjpeg_dec.cpp#L28

With that line, I'm seeing an error "Unsupported color conversion request"

When I remove that line and rebuild and run, the tool no longer hangs.

Edit 2:

Looks like the problem is specific to certain images. The one supplied by @den1a seems to have a jpeg_color_space that does not support the requested conversion: it's `JCS_YCCK` instead of one of `JCS_GRAYSCALE`, `JCS_RGB`, and `JCS_YCbCr`: which fails [here](https://github.com/mozilla/mozjpeg/blob/323469818c94374c200df2fdd11695dc4ece5b6f/jdcolor.c#L806)

I feel like this issue isn't limited to Windows only.

Edit 3:
Refer to #348 for color issue, CMYK/YCCK being problematic seems to be a known issue.

**Comment by Abromeit** [comment]
The other day i converted 2500 jpeg images to avif without running into this issue.
Today i started another run with 2000 additional images (taken from the same website). 
– Had several _"Unsupported color conversion request"_ messages and **decoding** seemingly stopped at file 303.  Hm…

After poking around for some time with exiftool, imagick and photoshop i tried this (fish shell, sorry):
```fish
for file in (find . -name '*.jpg' -type f );
    set -l c (magick identify -format "%[colorspace]" "$file")
    if test "$c" = 'CMYK'
        mv "$file" "./_files-to-ignore/$file";
    end;
end;
```
This solved my issue and i could successfully convert the remaining images.

**Comment by den1a** [comment]
Up to this point, I used a timeout to skip such images and wrote them to the database as problematic files. After finding @Abromeit, I decided to check the color scheme. And indeed all the problematic photos have a CMYK scheme

**Comment by meotimdihia** [comment]
> Thank you! I’ll investigate. My hunch is that this is related to Windows.

My Ubuntu server is happening this problem too.
![Code_2022-01-18_22-48-45](https://user-images.githubusercontent.com/300961/149970723-2bfdbe6a-d67b-43f1-929f-edd37f11c136.png)

**Comment by lonix1** [comment]
I am also on ubuntu, and also get this problem.

Some of my files were CMYK. I converted to sRGB and the problem went away. Thanks @Abromeit !

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
