### ISSUE TITLE
Segmentation fault when running Squoosh with Node 16 (ARM)

### ISSUE THREAD

**Issue by trm217** [GoogleChromeLabs/squoosh#1056]
**Describe the bug**
Squoosh causes a segmentation fault when compressing images when using Node V16 (ARM build).

**To Reproduce**
1. Install Node 16 (ARM native version) on an ARM device. (The error will not occur with non ARM versions of node)
2. Clone this [repository](https://github.com/trm217/reproduce-squoosh-segmentation-fault-on-arm) that contains a simple node application that converts a jpg and png to webp using squoosh. 
3. Install the dependencies.
4. Run the index.js script.
5. See the following error:
<img width="276" alt="Screenshot 2021-06-16 at 10 37 43" src="https://user-images.githubusercontent.com/30313631/122186994-e524bc80-ce8e-11eb-803a-ee05025cdf49.png">

**Expected behavior**
Squoosh should be able to convert the images to WEBP without causing a segmentation vault when using the ARM native Node V16.

**Version:**
 - OS w/ version: macOS Big Sur 11.4
 - Node version: 16.3.0
 - npm version: 7.15.1

**Additional context, screenshots, screencasts**
This issue first came up in the following [issue](https://github.com/vercel/next.js/issues/24421) on the next.js repository.

**Comment by surma** [comment]
I just published `@squoosh/lib` v0.3.0 which has a rebuild of all our codecs. I just tested it on my M1 with Node 16 and it worked. Can you give it another try?

I’ll close this bug, but please re-open if it’s still breaking for you!

**Comment by trm217** [comment]
@surma The reproduction I shared still throws an error for me: `zsh: bus error  node index.js` (after upgrading to v0.3.1)

**Comment by surma** [comment]
Interesting. You seem to have found a v8 bug with WebAssembly on M1 here.

Your test case works fine if we disable the optimizing compiler: `node --no-wasm-tier-up ./index.js`

I’ll see if I can get this reduced further to forward to the v8 team.

**Comment by surma** [comment]
Another fun thing: It also doesn’t crash (for me) if I restrict v8’s thread pool size to < 4: `node --v8-pool-size=3 ./index.js`

**Comment by surma** [comment]
So it seems to be an upgrade issue. If I disable either the baseline compiler or the optimizing compiler, everything works fine. If I wait like 500ms before invoking the webp encoder, everything works fine. It seems that the Wasm module starts running with the output from the baseline compiler but then switches over to the output of the opimizing compiler and that makes it fail. The issue also happens with AVIF and WebP2, but not with JPEG-XL, MozJPEG or OxiPNG.

Sadly, I haven’t been able to reproduce that issue in a smaller test-case.

**Comment by trm217** [comment]
Sounds interesting! Unfortunately my knowledge of WASM is fairly limited 😅 
Thanks for looking into it! 🙏🏻
What kind of a smaller reproduction would you need?

**Comment by surma** [comment]
Talked to the v8 team. It is likely that this bug has been fixed a couple of days ago, and the fix should be included as of v8 9.3.

I checked the nightlies of Node 17, which is still based on v8 9.1, so we’ll have to wait a couple of days until I can check that this is indeed fixed.

Until then, I’m trying to figure out if there is a user-land workaround. I know that waiting ~100ms between Wasm instantiation and Wasm usage can significantly reduce the chances of the error happening, but not sure how to expose that or bake that in.

**Comment by styfle** [comment]
@surma Which version of Node.js was it fixed in?

I was still able to reproduce with Node.js `v17.0.0-nightly202107074de6f207dc` that was built today.

```
git clone https://github.com/trm217/reproduce-squoosh-segmentation-vault-on-arm
cd reproduce-squoosh-segmentation-vault-on-arm
curl https://nodejs.org/download/nightly/v17.0.0-nightly202107074de6f207dc/node-v17.0.0-nightly202107074de6f207dc-darwin-arm64.tar.gz | tar -zx
./node-v17.0.0-nightly202107074de6f207dc-darwin-arm64/bin/node index.js
```

**Comment by surma** [comment]
It was fixed is _no_ version of Node as of yet. I thought it was fixed in *v8* v9.3 (you can see your v8 version via `process.versions.v8`). But they found another bug related to this on M1, so my hunch is that we have to wait for v8 v9.4.

**Comment by trm217** [comment]
> It was fixed is _no_ version of Node as of yet. I thought it was fixed in _v8_ v9.3 (you can see your v8 version via `process.versions.v8`). But they found another bug related to this on M1, so my hunch is that we have to wait for v8 v9.4.

Are these issues tracked somewhere that are publicly accessible?

**Comment by surma** [comment]
Sure: https://crbug.com/1224882

**Comment by surma** [comment]
Opened a bug on Node to backport the fix to Node 16: https://github.com/nodejs/node/issues/39327

**Comment by trm217** [comment]
The underlying issue is reported to be fixed as of Node 16.5.
Ref:
https://github.com/vercel/next.js/issues/24421#issuecomment-880060070

**Comment by soasada** [comment]
Hi! I'm having the same error than this thread is talking about. My mac is an intel one x86. I'm using **@squoosh/lib** 0.4.0 and trying to do a simple webservice to optimize image size with express.js. 

I'm getting: `zsh: bus error npm run start` error every time I try to encode an image.

**Steps to reproduce:**

1. Install Node 16 LTS, last version the time writing this is: 16.13.1.
2. Run the code that I will paste here.
3. Run `npm run start`.
4. Post an image, I'm testing with a 35MB image png.

**index.mjs**

```javascript
import express from 'express';
import formidable from 'formidable';
import fs from 'fs';
import {cpus} from 'os';
import {ImagePool} from '@squoosh/lib';

const app = express();
const port = 9091;

app.post('/squoosh', (req, res) => {
  const form = formidable({});

  form.parse(req, async (err, fields, files) => {
    if (err) {
      console.log(err);
      return;
    }

    const file = files.file[0];

    if (file) {
      const data = fs.readFileSync(file.filepath);
      const imagePool = new ImagePool(cpus().length);
      const image = imagePool.ingestImage(data);
      await image.decoded;

      const encodeOptions = {
        mozjpeg: {},
        jxl: {
          quality: 90,
        },
      };

      const optimizedImage = await image.encode(encodeOptions);
      console.log('Image encoded');
    }
  });
});

app.listen(port, () => {
  console.log(`App listening at http://localhost:${port}`);
});
```

**package.json**

```json
{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.mjs"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.2",
    "@squoosh/lib": "^0.4.0",
    "formidable": "^3.2.1"
  }
}
```

**Version:**

- OS w/ version: Monterey 12.0.1
- Node version: v16.13.1
- npm version: 8.1.2
- v8 version: 9.4.146.24-node.14
