### ISSUE TITLE
squoosh-cli resize error on windows

### ISSUE THREAD

**Issue by lx1054331851** [GoogleChromeLabs/squoosh#968]
```bash
C:\WINDOWS\system32>npx @squoosh/cli --resize '{"enabled":true,"width":2048,"height":1365,"method":"lanczos3","fitMethod":"stretch","premultiply":true,"linearRGB":true}' --mozjpeg '{"quality":75,"baseline":false,"arithmetic":false,"progressive":true,"optimize_coding":true,"smoothing":0,"color_space":3,"quant_table":3,"trellis_multipass":false,"trellis_opt_zero":false,"trellis_opt_table":false,"trellis_loops":1,"auto_subsample":true,"chroma_subsample":2,"separate_chroma_quality":false,"chroma_quality":75}' -d d:\1 "D:\2022\FC2022SS00001.jpg"
```

With the resize option as up there, error occurred :
```bash
1/1 \ ▐▨▨▨▨▨╌╌╌╌╌▌ Decoding...
 D:\2022\FC2022SS00001.jpg: 5.12MBError: Need to specify at least width or height when resizing
    at resizeWithAspect (C:\Users\lx105\AppData\Roaming\npm\node_modules\@squoosh\cli\build\index.js:7:376302)
    at C:\Users\lx105\AppData\Roaming\npm\node_modules\@squoosh\cli\build\index.js:7:376891
    at preprocessImage (C:\Users\lx105\AppData\Roaming\npm\node_modules\@squoosh\cli\build\index.js:7:520890)
    at async MessagePort.<anonymous> (C:\Users\lx105\AppData\Roaming\npm\node_modules\@squoosh\cli\build\index.js:7:492960)
Worker error:  Error [RuntimeError]: abort(Error: Need to specify at least width or height when resizing). Build with -s ASSERTIONS=1 for more info.
    at process.w (C:\Users\lx105\AppData\Roaming\npm\node_modules\@squoosh\cli\build\index.js:7:360765)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
1/1 | ▐▨▨▨▨▨╌╌╌╌╌▌ Decoding...
```

When I remove the resize option, the program run successfully.
```bash
C:\WINDOWS\system32>npx @squoosh/cli --mozjpeg '{"quality":75,"baseline":false,"arithmetic":false,"progressive":true,"optimize_coding":true,"smoothing":0,"color_space":3,"quant_table":3,"trellis_multipass":false,"trellis_opt_zero":false,"trellis_opt_table":false,"trellis_loops":1,"auto_subsample":true,"chroma_subsample":2,"separate_chroma_quality":false,"chroma_quality":75}' -d d:\1 "D:\2022\FC2022SS00001.jpg"
```
```bash
1/1 √ Squoosh results:
 D:\2022\FC2022SS00001.jpg: 5.12MB
  └ .jpg  → 480.70KB (9.17%)
```

But when I run cli on mac os, I have not meet the problem!

**Comment by lx1054331851** [comment]
Another error:  WebAssembly.Memory(): could not allocate memory

```bash
[RangeError: WebAssembly.instantiate(): Out of memory: wasm memory]
Worker error:  Error [RuntimeError]: abort(RangeError: WebAssembly.instantiate(): Out of memory: wasm memory). Build with -s ASSERTIONS=1 for more info.
    at process.w (C:\Users\lx105\AppData\Roaming\npm\node_modules\@squoosh\cli\build\index.js:7:360765)
    at process.emit (events.js:327:22)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
RangeError: WebAssembly.Memory(): could not allocate memory
    at C:\Users\lx105\AppData\Roaming\npm\node_modules\@squoosh\cli\build\index.js:7:176011
    at instantiateEmscriptenWasm (C:\Users\lx105\AppData\Roaming\npm\node_modules\@squoosh\cli\build\index.js:7:153532)
    at Object.dec (C:\Users\lx105\AppData\Roaming\npm\node_modules\@squoosh\cli\build\index.js:7:378384)
    at decodeFile (C:\Users\lx105\AppData\Roaming\npm\node_modules\@squoosh\cli\build\index.js:7:520655)
    at async MessagePort.<anonymous> (C:\Users\lx105\AppData\Roaming\npm\node_modules\@squoosh\cli\build\index.js:7:492960)
Worker error:  Error [RuntimeError]: abort(RangeError: WebAssembly.Memory(): could not allocate memory). Build with -s ASSERTIONS=1 for more info.
    at process.w (C:\Users\lx105\AppData\Roaming\npm\node_modules\@squoosh\cli\build\index.js:7:360765)
    at process.emit (events.js:327:22)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

**Comment by Giacomo411** [comment]
Can you try using this for the resize:
`--resize {"enabled":true,"width":2048,"height":1365,"method":'lanczos3',"fitMethod":'stretch',"premultiply":true,"linearRGB":true}`

**Comment by Frank12-12** [comment]
Same issue here. Removing all single Quotes before the options and then replacing all double quotes by single quotes worked for me.

**Comment by robhawkes** [comment]
> Same issue here. Removing all single Quotes before the options and then replacing all double quotes by single quotes worked for me.

This fixed the memory error for me too — specifically, swapping double and single quotes.

**Comment by surma** [comment]
I just published `@squoosh/cli` v0.7.1 which has a lot of fixes. Can you give it another try?

I’ll close this bug, but please re-open if it’s still breaking for you!

**Comment by asiontang** [comment]
```cmd
squoosh-cli.cmd --resize "{""enabled"":true,""width"":360,""height"":360,""method"":""hqx"",""fitMethod"":""stretch"",""premultiply"":false,""linearRGB"":false}" %1
```
this worked for me.

**Comment by kirilloid** [comment]
I still have the same bug, worked with `--resize {'enabled':true,'width':360,...` as @Frank12-12 suggested
BTW @surma maybe, just create another button in UI: copy options for CLI on windows?
I can do the PR, but would like to know if this idea is accepted in general.
