### ISSUE TITLE
[CLI] Batch Conversion fail

### ISSUE THREAD

**Issue by ianzhuo** [GoogleChromeLabs/squoosh#973]
Hi, 
there seems some path issue when batch conversion on windows 10. 

![image](https://user-images.githubusercontent.com/1394735/110889181-a845a880-8328-11eb-9b0b-4430c903f9c0.png)

**Comment by surma** [comment]
I just published `@squoosh/cli` v0.7.1 which should fix this. Can you give it another try?

I’ll close this bug, but please re-open if it’s still breaking for you!

**Comment by ianzhuo** [comment]
@surma  
Thanks for your help.
However, after upgrading to 0.7.1 still encounter error as below. 😢

## CMD
```powershell
d:\test>npm ls -g
C:\Users\b06065\AppData\Roaming\npm
├── @squoosh/cli@0.7.1
├── neovim@4.9.0
├── pyright@1.1.101
└── vim-language-server@2.1.2
```

```powershell
d:\test>npx @squoosh/cli -V
error: unknown option '-V'
npm ERR! code 1
npm ERR! path d:\test
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c squoosh-cli -V

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\b06065\AppData\Local\npm-cache\_logs\2021-06-17T01_33_13_040Z-debug.log
```

## 2021-06-17T01_33_13_040Z-debug.log result
```powershell
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   '@squoosh/cli',
0 verbose cli   '-V'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.5.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:d:\test\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\b06065\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\b06065\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 verbose npm-session d99ac022c7552c79
20 timing npm:load Completed in 17ms
21 http fetch GET 304 https://registry.npmjs.org/@squoosh%2fcli 328ms (from cache)
22 timing arborist:ctor Completed in 1ms
23 timing arborist:ctor Completed in 0ms
24 timing arborist:ctor Completed in 0ms
25 timing command:exec Completed in 556ms
26 verbose stack Error: command failed
26 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
26 verbose stack     at ChildProcess.emit (node:events:376:20)
26 verbose stack     at maybeClose (node:internal/child_process:1063:16)
26 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
27 verbose cwd d:\test
28 verbose Windows_NT 10.0.19043
29 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "exec" "--" "@squoosh/cli" "-V"
30 verbose node v15.5.1
31 verbose npm  v7.3.0
32 error code 1
33 error path d:\test
34 error command failed
35 error command C:\WINDOWS\system32\cmd.exe /d /s /c squoosh-cli -V
36 verbose exit 1
```

**Comment by surma** [comment]
`-V` is not a valid flag. Can you try if your actual conversion works or if it still fails?

**Comment by ianzhuo** [comment]
It doesn't seem to work.

```batch
C:\test>npx @squoosh/cli --mozjpeg '{}' 1.jpg
0/1 / ▐╌╌╌╌╌╌╌╌╌╌▌ Decoding...
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Cannot use 'in' operator to search for 'quality' in {}".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

C:\test>npx @squoosh/cli --mozjpeg '{}' *.jpg
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, lstat 'C:\test\*.jpg'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'C:\\test\\*.jpg'
}
```

**Comment by surma** [comment]
Okay interesting. I wonder if this is Windows related, because I can’t reproduce this.

**Comment by surma** [comment]
Looking into this, ti seems the wildcards are not working in Windows.

@samdutton is working on adding globs, so this will hopefully get solved through his work!

**Comment by Nantris** [comment]
Any update on glob support? I had thought it was already supported from reading some other comment, but I guess not.

Even being able to do `./icons/*.png` would be a huge help, and a lot easier than full glob support. Implementing Squoosh for even our simple use case was very difficult due to the rigidness of the API.

It's a great project, I really hope this is added!

**Comment by Th3S4mur41** [comment]
Same here...
`squoosh-cli --webp auto icons/android*.png` works fine when executed directly in bash/WSL but not on Windows (e.g. from a script in package.json)

**Comment by digiage** [comment]
> Same here...
> `squoosh-cli --webp auto icons/android*.png` works fine when executed directly in bash/WSL but not on Windows

@Th3S4mur41  can you please share how did you make it work on WSL? Thanks

**Comment by Th3S4mur41** [comment]
@digiage starting my Ubuntu WSL in Windows Terminal then navigating to my icons folder and ran the script as seen in the screenshot. Nothing special
![image](https://user-images.githubusercontent.com/5543595/177282933-cb5be158-9e02-464e-8067-01c546876cfa.png)
Does that answer your question or do you have a specific problem making it work?

**Comment by digiage** [comment]
> starting my Ubuntu WSL in Windows Terminal then navigating to my icons folder and ran the script as seen in the screenshot. Nothing special

@Th3S4mur41 thanks. I was getting the "bash\r: No such file or directory" error (which was totally incomprehensible for me), but in the end I did make it work by installing Node 16.15.1 (v18 did not work) on WSL. I did not realize at first that Node installed on my Windows machine is not enough.

**Comment by Th3S4mur41** [comment]
Right, I remember that one... Faced it too when I updated my WSL to Ubuntu 22 😅

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
